# @AlterVision.Api_HostAddress = http://localhost:5036

# GET {{AlterVision.Api_HostAddress}}/weatherforecast/
# Accept: application/json


@AlterVision.Api_HostAddress = https://localhost:7073

# Health com token
GET {{AlterVision.Api_HostAddress}}/api/Health
Accept: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbHRlcnZpc2lvbiIsImlkX3RlcmNlaXJvIjoiMSIsIm5vbWUiOiJBbHRlclZpc2lvbkFwaSIsImNsaWVudF9pZCI6ImFsdGVydmlzaW9uIiwiZXhwIjoxNzgxMjcxMTk2LCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.H1xgOVNEGwSvLiHOOouEAhD7ZzBBbOs9g9YzwSz8Chg



###
