@SantaLolla.Api_HostAddress = https://localhost:7073

# Health com token
GET {{SantaLolla.Api_HostAddress}}/api/Health
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbHRlcnZpc2lvbiIsImlkX3RlcmNlaXJvIjoiMSIsIm5vbWUiOiJBbHRlclZpc2lvbkFwaSIsImNsaWVudF9pZCI6ImFsdGVydmlzaW9uIiwiZXhwIjoxNzgxMjgwMTQyLCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.vKZ5hp0TpmWvymZj3oPfPHLPAYd5Ev3aukCTXNOKO3A


@SantaLolla.Api_HostAddress = https://localhost:7073

### Listar lojas sem token - deve retornar 401
GET {{SantaLolla.Api_HostAddress}}/api/Lojas
Accept: application/json


### Listar lojas com token - deve retornar 200
GET {{SantaLolla.Api_HostAddress}}/api/Lojas
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbHRlcnZpc2lvbiIsImlkX3RlcmNlaXJvIjoiMSIsIm5vbWUiOiJBbHRlclZpc2lvbkFwaSIsImNsaWVudF9pZCI6ImFsdGVydmlzaW9uIiwiZXhwIjoxNzgxMjgwMTQyLCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.vKZ5hp0TpmWvymZj3oPfPHLPAYd5Ev3aukCTXNOKO3A

### Listar vendedores sem token - deve retornar 401
GET {{SantaLolla.Api_HostAddress}}/api/Vendedores
Accept: application/json


### Listar vendedores com token - deve retornar 200
GET {{SantaLolla.Api_HostAddress}}/api/Vendedores
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbHRlcnZpc2lvbiIsImlkX3RlcmNlaXJvIjoiMSIsIm5vbWUiOiJBbHRlclZpc2lvbkFwaSIsImNsaWVudF9pZCI6ImFsdGVydmlzaW9uIiwiZXhwIjoxNzgxMjgwMTQyLCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.vKZ5hp0TpmWvymZj3oPfPHLPAYd5Ev3aukCTXNOKO3A

###

### Listar vendas por rede e loja
GET {{SantaLolla.Api_HostAddress}}/api/Vendas?rede=rede000001&codigoLoja=00000001&dataInicio=2026-06-13&dataFim=2026-06-13
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTYW50YUxvbGxhIiwiaWRfdGVyY2Vpcm8iOiIyIiwibm9tZSI6IlNhbnRhTG9sbGFBcGkiLCJjbGllbnRfaWQiOiJTYW50YUxvbGxhIiwiZXhwIjoxNzgxNTMzODI2LCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.sFLgF7_KBNvp27RXN5y63jo7fQ4HEZm6QvmNE0eutk0

GET {{SantaLolla.Api_HostAddress}}/api/Lojas?lastUpdateInicio=2026-06-11T00:00:00&lastUpdateFim=2026-06-12T23:59:59&pagina=1&tamanhoPagina=500
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTYW50YUxvbGxhIiwiaWRfdGVyY2Vpcm8iOiIyIiwibm9tZSI6IlNhbnRhTG9sbGFBcGkiLCJjbGllbnRfaWQiOiJTYW50YUxvbGxhIiwiZXhwIjoxNzgxNTMzODI2LCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.sFLgF7_KBNvp27RXN5y63jo7fQ4HEZm6QvmNE0eutk0

GET {{SantaLolla.Api_HostAddress}}/api/Lojas?rede=rede000001&pagina=1&tamanhoPagina=500
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTYW50YUxvbGxhIiwiaWRfdGVyY2Vpcm8iOiIyIiwibm9tZSI6IlNhbnRhTG9sbGFBcGkiLCJjbGllbnRfaWQiOiJTYW50YUxvbGxhIiwiZXhwIjoxNzgxNTMzODI2LCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.sFLgF7_KBNvp27RXN5y63jo7fQ4HEZm6QvmNE0eutk0

GET {{SantaLolla.Api_HostAddress}}/api/Lojas?rede=rede000001&codigoLoja=00000001
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTYW50YUxvbGxhIiwiaWRfdGVyY2Vpcm8iOiIyIiwibm9tZSI6IlNhbnRhTG9sbGFBcGkiLCJjbGllbnRfaWQiOiJTYW50YUxvbGxhIiwiZXhwIjoxNzgxNTMzODI2LCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.sFLgF7_KBNvp27RXN5y63jo7fQ4HEZm6QvmNE0eutk0

GET {{SantaLolla.Api_HostAddress}}/api/Vendedores?lastUpdateInicio=2026-06-11T00:00:00&lastUpdateFim=2026-06-12T23:59:59&pagina=1&tamanhoPagina=500
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTYW50YUxvbGxhIiwiaWRfdGVyY2Vpcm8iOiIyIiwibm9tZSI6IlNhbnRhTG9sbGFBcGkiLCJjbGllbnRfaWQiOiJTYW50YUxvbGxhIiwiZXhwIjoxNzgxNTMzODI2LCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.sFLgF7_KBNvp27RXN5y63jo7fQ4HEZm6QvmNE0eutk0

GET {{SantaLolla.Api_HostAddress}}/api/Vendedores?rede=rede000001&codigoLoja=00000001&pagina=1&tamanhoPagina=500
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTYW50YUxvbGxhIiwiaWRfdGVyY2Vpcm8iOiIyIiwibm9tZSI6IlNhbnRhTG9sbGFBcGkiLCJjbGllbnRfaWQiOiJTYW50YUxvbGxhIiwiZXhwIjoxNzgxNTMzODI2LCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.sFLgF7_KBNvp27RXN5y63jo7fQ4HEZm6QvmNE0eutk0

GET {{SantaLolla.Api_HostAddress}}/api/Vendedores?rede=rede000001&codigoLoja=00000001&codigoVendedor=00084745
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTYW50YUxvbGxhIiwiaWRfdGVyY2Vpcm8iOiIyIiwibm9tZSI6IlNhbnRhTG9sbGFBcGkiLCJjbGllbnRfaWQiOiJTYW50YUxvbGxhIiwiZXhwIjoxNzgxNTMzODI2LCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.sFLgF7_KBNvp27RXN5y63jo7fQ4HEZm6QvmNE0eutk0

### Listar estoques sem token - deve retornar 401
GET {{SantaLolla.Api_HostAddress}}/api/Estoques
Accept: application/json


### Listar estoques com token
GET {{SantaLolla.Api_HostAddress}}/api/Estoques?pagina=1&tamanhoPagina=500
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTYW50YUxvbGxhIiwiaWRfdGVyY2Vpcm8iOiIyIiwibm9tZSI6IlNhbnRhTG9sbGFBcGkiLCJjbGllbnRfaWQiOiJTYW50YUxvbGxhIiwiZXhwIjoxNzgxNTMzODI2LCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.sFLgF7_KBNvp27RXN5y63jo7fQ4HEZm6QvmNE0eutk0


### Listar estoque por loja
GET {{SantaLolla.Api_HostAddress}}/api/Estoques?rede=rede000001&codigoLoja=01&pagina=1&tamanhoPagina=500
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTYW50YUxvbGxhIiwiaWRfdGVyY2Vpcm8iOiIyIiwibm9tZSI6IlNhbnRhTG9sbGFBcGkiLCJjbGllbnRfaWQiOiJTYW50YUxvbGxhIiwiZXhwIjoxNzgxNTMzODI2LCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.sFLgF7_KBNvp27RXN5y63jo7fQ4HEZm6QvmNE0eutk0


### Listar estoque por produto
GET {{SantaLolla.Api_HostAddress}}/api/Estoques?codigoProduto=123456&pagina=1&tamanhoPagina=500
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTYW50YUxvbGxhIiwiaWRfdGVyY2Vpcm8iOiIyIiwibm9tZSI6IlNhbnRhTG9sbGFBcGkiLCJjbGllbnRfaWQiOiJTYW50YUxvbGxhIiwiZXhwIjoxNzgxNTMzODI2LCJpc3MiOiJBbHRlclZpc2lvbi5BcGkiLCJhdWQiOiJBbHRlclZpc2lvbi5UZXJjZWlyb3MifQ.sFLgF7_KBNvp27RXN5y63jo7fQ4HEZm6QvmNE0eutk0


### Listar estoque por referência
GET {{SantaLolla.Api_HostAddress}}/api/Estoques?referencia=ABC123&pagina=1&tamanhoPagina=500
Accept: application/json
